### ISSUE TITLE
Hidden assignments yields error for anonymous users

### ISSUE THREAD

**Issue by torgeirl** [devilry/trix2#79]
[An `if` test for hidden assignments](https://github.com/devilry/trix2/blob/master/trix/trix_student/views/common.py#L47) yields `AttributeError: 'AnonymousUser' object has no attribute 'is_admin'`.

It seems the error is non-critical and runs silent in the background so it shouldn't effect anonymous users' access to the service.

**Comment by torgeirl** [comment]
**Suggested solution**
Make `hidden=True` the default, and set `hidden=False` iff user is authenticated and is_admin.

**Comment by Elthan** [comment]
Was this fixed by #81 ?

**Comment by torgeirl** [comment]
#81 didn't fix it, and got reverted in #82 (seems I forgot to tag this issue when reverting).

**Comment by Elthan** [comment]
Unable to reproduce this error. _get_progress should never be called when a user is not logged in since it called by the [AssignmentListProgressController](https://github.com/devilry/trix2/blob/fc339422729bd81823b95622b5a4f733ae9f1513/trix/trix_student/static/trix_student/src/app/assignments/controllers.coffee#L113) which is not included unless the [user is authenticated](https://github.com/devilry/trix2/blob/fc339422729bd81823b95622b5a4f733ae9f1513/trix/trix_student/templates/trix_student/assignment_list_base.django.html#L13).

Are you still getting these errors?

**Comment by torgeirl** [comment]
@Elthan: we received the last error report yesterday; 45 reports over the last 30 days.
